name: "CI"
# When this workflow should be executed
on:
  # Type of event
  pull_request:
    # Only against branches
    branches:
      - main

jobs:
  CI:
    # The operating system used by the workflow runner
    runs-on: ubuntu-latest

    # Set of permissions required by this workflow
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    # The steps to execute
    steps:
      # First checkout the repository
      - uses: actions/checkout@v4
      # Then install node on the runner
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          # Specify the required version of node
          node-version: "20.x"

      # Our project has dependencies, install these
      - name: "Install Deps"
        run: npm install

      # Run the tests
      - name: "Test"
        run: npm run test
